completed-react-effects-Bishan-Webeshete
BishanWebeshete/c0123-code-solutions pull request #118
Opened 2023-04-03 03:02 UTC by BishanWebeshete

![Kapture 2023-04-02 at 20 00 38](https://user-images.githubusercontent.com/121692569/229401816-b9f92d7b-cddd-4979-afd9-0e9cabcf8f6b.gif)

2023-04-03 16:04 UTC, RobertGardner requested changes

2023-04-03 16:04 UTC, RobertGardner commented on react-effects/my-app/src/List.js
> +        setError(value);
set isLoading to false here so the Loading... message doesn't stay there when there's an error.

2023-04-04 03:07 UTC, BishanWebeshete commented on react-effects/my-app/src/List.js
> +  }, [isLoading])
I got a linter warning when trying to leave the array empty so I kept isLoading in my dependencies.

2023-04-04 03:09 UTC, BishanWebeshete commented
updated react-effects to set isLoading properly

2023-04-04 15:24 UTC, RobertGardner approved these changes

2023-04-04 15:24 UTC, RobertGardner commented on react-effects/my-app/src/List.js
> +  }, [isLoading])
Oh, that's correct because you check `if (isLoading)` in your Effect. Well done.

2023-04-04 15:59 UTC, merged