completed-node-notes-cli-Bishan-Webeshete
BishanWebeshete/c0123-code-solutions pull request #84
Opened 2023-03-17 22:43 UTC by BishanWebeshete

![Screen Shot 2023-03-17 at 3 42 48 PM](https://user-images.githubusercontent.com/121692569/226065064-7c67a404-2e3e-4e89-9bf2-ea2c5d44cdc1.jpg)

2023-03-20 16:21 UTC, RobertGardner requested changes
You need to make up your mind -- promises or callbacks. You can't have it both ways! ;-) ;-)

2023-03-20 16:21 UTC, RobertGardner commented on node-notes-cli/add.js
> +  await writeFile('data.json', JSON.stringify(json, null, 2), (err) => {
This is using both `await` and a callback???

Fix all of them.

2023-03-26 21:16 UTC, BishanWebeshete commented
The proper updates have now been made.

2023-03-27 18:23 UTC, RobertGardner approved these changes

2023-03-27 19:10 UTC, merged